name: TestHMS
description: Example of setting custom map styles in HMS Map Kit

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_map: ^5.0.3+302

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/mapstyle_night_hms.json